import React from "react";
import PopularMovies from "../../components/templates/PopularMovieList";
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

const PopularMoviePages = () => {
    return(
        <>
        <Head>
            <title>Popular Movie</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
         <main className={styles.main}>
            <h1 className={styles.title}>
                Movie App
             </h1>
            <PopularMovies/>
        </main>
      </>
    )
}

export default PopularMoviePages;