import React from "react";
import Head from 'next/head'
import { useRouter } from "next/router";
import styles from '../../../styles/Home.module.css'


const DetailMovie = () => {
    const router = useRouter()
    const { movieId } = router.query
    return(
        <>
        <Head>
            <title>Detail Movie</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
         <main className={styles.main}>
            <h1 className={styles.title}>
                Movie App
            </h1>
            {movieId}
        </main>
      </>
    )
}

export default DetailMovie;